name = "runninghub-video-chroma-worker"
main = "runninghub-video-chroma-worker.js"
compatibility_date = "2025-01-01"

[vars]
RUNNINGHUB_VIDEO_CHROMA_APP_ID = "1893587363086417921"
RUNNINGHUB_VIDEO_CHROMA_CREATE_ENDPOINT = "https://www.runninghub.cn/openapi/v2/run/ai-app/1893587363086417921"
