name = "runninghub-video-upscale-worker"
main = "runninghub-video-upscale-worker.js"
compatibility_date = "2025-01-01"

[vars]
RUNNINGHUB_VIDEO_UPSCALE_APP_ID = "2033815457634983938"
RUNNINGHUB_VIDEO_UPSCALE_CREATE_ENDPOINT = "https://www.runninghub.cn/openapi/v2/run/ai-app/2033815457634983938"
